export const keycodeMapping = {
  Control: "LCTL",
  Shift: "LSHFT",
  Meta: "LGUI",
  Alt: "LALT",
  " ": "SPC",
  Tab: "TAB",
  Enter: "ENT",
  "[": "LBRC",
  "]": "RBRC",
  ArrowLeft: "LEFT",
  arrowRight: "RIGHT",
  ArrowUp: "UP",
  ArrowDown: "DOWN",
  Backspace: "BSPC",
  "\\": "GRV",
  ",": "COMM",
  ".": "DOT",
  "?": "SLSH",
  ";": "SCLN",
};
